# Generated by Django 4.2.3 on 2024-04-06 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('author', models.CharField(db_index=True, max_length=150, null=True)),
                ('date', models.CharField(db_index=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='product/%Y/%m/%d')),
                ('file', models.FileField(blank=True, max_length=255, upload_to='books/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.category')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'slug'], name='books_books_name_31156a_idx')],
            },
        ),
    ]
