# Generated by Django 4.2.3 on 2024-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='books/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='product/%Y/%m/%d'),
        ),
    ]
